import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_DAYS=int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS",30))

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT",587))
EMAIL_USERNAME = os.getenv("EMAIL_USERNAME")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")

OTP_EXPIRE_MINUTES = int(os.getenv("OTP_EXPIRE_MINUTES",5))
OTP_RESEND_COOLDOWN = int(os.getenv("OTP_RESEND_COOLDOWN",30))
MAX_OTP_ATTEMPTS = int(os.getenv("MAX_OTP_ATTEMPTS",5))


REDIS_HOST = os.getenv("REDIS_HOST","localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT",6379))
REDIS_DB = int(os.getenv("REDIS_DB",0))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

LOGIN_MAX_ATTEMPTS = 5
LOGIN_LOCK_TIME =300


